#!/usr/bin/env node
// Verifies candidate ATS board tokens against the real, live public APIs
// before they're allowed into sql/seed.sql. Prints a confirmed/dead report
// and writes sql/seed.sql from only the confirmed rows.
//
// Usage: node scripts/verify-sources.mjs

const GREENHOUSE_CANDIDATES = [
  "airbnb", "stripe", "doordash", "coinbase", "robinhood", "databricks",
  "notion", "affirm", "asana", "pinterest", "lyft", "reddit", "roblox",
  "squarespace", "gitlab", "discord", "figma", "instacart", "cloudflare",
  "okta", "twilio", "hashicorp",
];

const LEVER_CANDIDATES = [
  "palantir", "ramp", "brex", "plaid", "attentive", "box", "eventbrite",
  "yelp", "netflix", "canva", "shopify",
];

const ASHBY_CANDIDATES = [
  "linear", "vercel", "retool", "openai", "anthropic", "mercury", "replit",
  "scale", "deel", "webflow", "loom", "notion", "ramp", "brex",
];

async function checkGreenhouse(token) {
  const url = `https://boards-api.greenhouse.io/v1/boards/${token}/jobs`;
  try {
    const res = await fetch(url);
    if (!res.ok) return { token, ok: false, status: res.status };
    const data = await res.json();
    const count = Array.isArray(data.jobs) ? data.jobs.length : 0;
    return { token, ok: count > 0, status: res.status, count };
  } catch (e) {
    return { token, ok: false, error: e.message };
  }
}

async function checkLever(token) {
  const url = `https://api.lever.co/v0/postings/${token}?mode=json`;
  try {
    const res = await fetch(url);
    if (!res.ok) return { token, ok: false, status: res.status };
    const data = await res.json();
    const count = Array.isArray(data) ? data.length : 0;
    return { token, ok: count > 0, status: res.status, count };
  } catch (e) {
    return { token, ok: false, error: e.message };
  }
}

async function checkAshby(token) {
  const url = `https://api.ashbyhq.com/posting-api/job-board/${token}`;
  try {
    const res = await fetch(url);
    if (!res.ok) return { token, ok: false, status: res.status };
    const data = await res.json();
    const count = Array.isArray(data.jobs) ? data.jobs.length : 0;
    return { token, ok: count > 0, status: res.status, count };
  } catch (e) {
    return { token, ok: false, error: e.message };
  }
}

async function checkYcAlgolia() {
  // YC Work at a Startup's public search runs on Algolia with an app ID and
  // search-only key embedded in workatastartup.com's own frontend bundle —
  // not a secret, but I'm not going to fabricate a plausible-looking key
  // here. Real values must be read from that page's network requests
  // (DevTools -> Network -> filter "algolia.net") and dropped into
  // n8n/workflows/ingestion-yc.json before this branch will work.
  return { ok: false, manual: true };
}

function esc(s) {
  return String(s).replace(/'/g, "''");
}

async function main() {
  const results = { greenhouse: [], lever: [], ashby: [] };

  console.log("Checking Greenhouse tokens...");
  for (const t of GREENHOUSE_CANDIDATES) {
    const r = await checkGreenhouse(t);
    results.greenhouse.push(r);
    console.log(`  ${r.ok ? "OK  " : "DEAD"} ${t}${r.count != null ? ` (${r.count} jobs)` : ""}${r.status ? ` [${r.status}]` : ""}`);
  }

  console.log("Checking Lever tokens...");
  for (const t of LEVER_CANDIDATES) {
    const r = await checkLever(t);
    results.lever.push(r);
    console.log(`  ${r.ok ? "OK  " : "DEAD"} ${t}${r.count != null ? ` (${r.count} jobs)` : ""}${r.status ? ` [${r.status}]` : ""}`);
  }

  console.log("Checking Ashby tokens...");
  for (const t of ASHBY_CANDIDATES) {
    const r = await checkAshby(t);
    results.ashby.push(r);
    console.log(`  ${r.ok ? "OK  " : "DEAD"} ${t}${r.count != null ? ` (${r.count} jobs)` : ""}${r.status ? ` [${r.status}]` : ""}`);
  }

console.log("YC Work at a Startup: SKIPPED — needs a real Algolia app ID/search key");
  console.log("  pulled from workatastartup.com's own network requests (see comment in checkYcAlgolia).");
  await checkYcAlgolia();

  const confirmed = {
    greenhouse: results.greenhouse.filter((r) => r.ok).map((r) => r.token),
    lever: results.lever.filter((r) => r.ok).map((r) => r.token),
    ashby: results.ashby.filter((r) => r.ok).map((r) => r.token),
  };

  const lines = [
    "-- Auto-generated by scripts/verify-sources.mjs — only confirmed-live tokens.",
    "-- Re-run the script periodically; ATS tokens do get retired/renamed.",
    "",
  ];
  for (const token of confirmed.greenhouse) {
    lines.push(`INSERT INTO company_sources (name, ats_type, identifier, active) VALUES ('${esc(token)}', 'greenhouse', '${esc(token)}', true) ON CONFLICT (ats_type, identifier) DO NOTHING;`);
  }
  for (const token of confirmed.lever) {
    lines.push(`INSERT INTO company_sources (name, ats_type, identifier, active) VALUES ('${esc(token)}', 'lever', '${esc(token)}', true) ON CONFLICT (ats_type, identifier) DO NOTHING;`);
  }
  for (const token of confirmed.ashby) {
    lines.push(`INSERT INTO company_sources (name, ats_type, identifier, active) VALUES ('${esc(token)}', 'ashby', '${esc(token)}', true) ON CONFLICT (ats_type, identifier) DO NOTHING;`);
  }
  lines.push(`INSERT INTO company_sources (name, ats_type, identifier, active) VALUES ('amazon', 'custom_json', 'amazon.jobs/en/search.json', true) ON CONFLICT (ats_type, identifier) DO NOTHING;`);

  const fs = await import("node:fs");
  fs.writeFileSync(new URL("../sql/seed.sql", import.meta.url), lines.join("\n") + "\n");

  console.log("\nSummary:");
  console.log(`  Greenhouse: ${confirmed.greenhouse.length}/${GREENHOUSE_CANDIDATES.length} confirmed`);
  console.log(`  Lever:      ${confirmed.lever.length}/${LEVER_CANDIDATES.length} confirmed`);
  console.log(`  Ashby:      ${confirmed.ashby.length}/${ASHBY_CANDIDATES.length} confirmed`);
  console.log("Wrote sql/seed.sql");
}

main();
