-- Auto-generated by scripts/verify-sources.mjs — only confirmed-live tokens.
-- Re-run the script periodically; ATS tokens do get retired/renamed.

INSERT INTO company_sources (name, ats_type, identifier, active) VALUES ('airbnb', 'greenhouse', 'airbnb', true) ON CONFLICT (ats_type, identifier) DO NOTHING;
INSERT INTO company_sources (name, ats_type, identifier, active) VALUES ('stripe', 'greenhouse', 'stripe', true) ON CONFLICT (ats_type, identifier) DO NOTHING;
INSERT INTO company_sources (name, ats_type, identifier, active) VALUES ('coinbase', 'greenhouse', 'coinbase', true) ON CONFLICT (ats_type, identifier) DO NOTHING;
INSERT INTO company_sources (name, ats_type, identifier, active) VALUES ('robinhood', 'greenhouse', 'robinhood', true) ON CONFLICT (ats_type, identifier) DO NOTHING;
INSERT INTO company_sources (name, ats_type, identifier, active) VALUES ('databricks', 'greenhouse', 'databricks', true) ON CONFLICT (ats_type, identifier) DO NOTHING;
INSERT INTO company_sources (name, ats_type, identifier, active) VALUES ('affirm', 'greenhouse', 'affirm', true) ON CONFLICT (ats_type, identifier) DO NOTHING;
INSERT INTO company_sources (name, ats_type, identifier, active) VALUES ('asana', 'greenhouse', 'asana', true) ON CONFLICT (ats_type, identifier) DO NOTHING;
INSERT INTO company_sources (name, ats_type, identifier, active) VALUES ('pinterest', 'greenhouse', 'pinterest', true) ON CONFLICT (ats_type, identifier) DO NOTHING;
INSERT INTO company_sources (name, ats_type, identifier, active) VALUES ('lyft', 'greenhouse', 'lyft', true) ON CONFLICT (ats_type, identifier) DO NOTHING;
INSERT INTO company_sources (name, ats_type, identifier, active) VALUES ('reddit', 'greenhouse', 'reddit', true) ON CONFLICT (ats_type, identifier) DO NOTHING;
INSERT INTO company_sources (name, ats_type, identifier, active) VALUES ('roblox', 'greenhouse', 'roblox', true) ON CONFLICT (ats_type, identifier) DO NOTHING;
INSERT INTO company_sources (name, ats_type, identifier, active) VALUES ('squarespace', 'greenhouse', 'squarespace', true) ON CONFLICT (ats_type, identifier) DO NOTHING;
INSERT INTO company_sources (name, ats_type, identifier, active) VALUES ('gitlab', 'greenhouse', 'gitlab', true) ON CONFLICT (ats_type, identifier) DO NOTHING;
INSERT INTO company_sources (name, ats_type, identifier, active) VALUES ('discord', 'greenhouse', 'discord', true) ON CONFLICT (ats_type, identifier) DO NOTHING;
INSERT INTO company_sources (name, ats_type, identifier, active) VALUES ('figma', 'greenhouse', 'figma', true) ON CONFLICT (ats_type, identifier) DO NOTHING;
INSERT INTO company_sources (name, ats_type, identifier, active) VALUES ('instacart', 'greenhouse', 'instacart', true) ON CONFLICT (ats_type, identifier) DO NOTHING;
INSERT INTO company_sources (name, ats_type, identifier, active) VALUES ('cloudflare', 'greenhouse', 'cloudflare', true) ON CONFLICT (ats_type, identifier) DO NOTHING;
INSERT INTO company_sources (name, ats_type, identifier, active) VALUES ('okta', 'greenhouse', 'okta', true) ON CONFLICT (ats_type, identifier) DO NOTHING;
INSERT INTO company_sources (name, ats_type, identifier, active) VALUES ('twilio', 'greenhouse', 'twilio', true) ON CONFLICT (ats_type, identifier) DO NOTHING;
INSERT INTO company_sources (name, ats_type, identifier, active) VALUES ('palantir', 'lever', 'palantir', true) ON CONFLICT (ats_type, identifier) DO NOTHING;
INSERT INTO company_sources (name, ats_type, identifier, active) VALUES ('linear', 'ashby', 'linear', true) ON CONFLICT (ats_type, identifier) DO NOTHING;
INSERT INTO company_sources (name, ats_type, identifier, active) VALUES ('openai', 'ashby', 'openai', true) ON CONFLICT (ats_type, identifier) DO NOTHING;
INSERT INTO company_sources (name, ats_type, identifier, active) VALUES ('replit', 'ashby', 'replit', true) ON CONFLICT (ats_type, identifier) DO NOTHING;
INSERT INTO company_sources (name, ats_type, identifier, active) VALUES ('notion', 'ashby', 'notion', true) ON CONFLICT (ats_type, identifier) DO NOTHING;
INSERT INTO company_sources (name, ats_type, identifier, active) VALUES ('ramp', 'ashby', 'ramp', true) ON CONFLICT (ats_type, identifier) DO NOTHING;
INSERT INTO company_sources (name, ats_type, identifier, active) VALUES ('amazon', 'custom_json', 'amazon.jobs/en/search.json', true) ON CONFLICT (ats_type, identifier) DO NOTHING;
